accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.login_user, name="login"),
    path("logout/", views.logout_user, name="logout")

]

bookreview/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include ('accounts.urls'))
]

main/urls.py
from django.urls import path
from .import views

app_name = "main"

urlpatterns = [
    path('', views.home, name="home"),
    path('details/<int:id>/', views.detail, name="detail"),
    path('addbooks/', views.add_books, name="add_books"),
    path('editbooks/<int:id>/', views.edit_books, name="edit_books"),
    path('deletebooks/<int:id>/', views.delete_books, name="delete_books"),
    path('addreview/<int:id>/', views.add_review, name="add_review"),
    path('editreview/<int:book_id>/<int:review_id>/', views.edit_review, name="edit_review"),
    path('deletereview/<int:book_id>/<int:review_id>/', views.delete_review, name="delete_review"),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Book(models.Model):
    #fields for book table
    name = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    description = models.TextField(max_length=5000)
    release_date = models.DateField()
    averageRating = models.FloatField(default=0)
    image = models.URLField(default=None, null=True)

    def __str__(self):
        return self.name
    
    def __unicode__(self):
        return self.name

class Review(models.Model):
    #fields for review table
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField(max_length=5000)
    rating = models.FloatField(default=0)

    def __str__(self):
        return self.user.username

main/forms.py
from django import forms
from .models import *

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('name', 'author', 'description', 'release_date', 'image')

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ("comment", "rating")

main/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse
from .models import *
from .forms import *
from django.db.models import Avg

# Create your views here.
#home
def home(request):
    query = request.GET.get("title")
    allBooks = None
    error = None
    #seach for book name
    if query:
        allBooks = Book.objects.filter(name__icontains=query)
        #check if query exists
        if not allBooks:
            error = "Title not found"
    #return all when empty
    else:
        allBooks = Book.objects.all()

    return render(request, 'main/index.html', {"books": allBooks, "error": error})

#details
def detail(request, id):
    book = Book.objects.get(id=id)
    reviews = Review.objects.filter(book=id).order_by("-comment")
    #calculate average
    average = reviews.aggregate(Avg("rating"))["rating__avg"]
    if average == None:
        average = 0
    average = round(average, 2)
    context = {
        "book": book,
        "reviews": reviews,
        "average": average
    }

    return render(request, 'main/details.html', context)
#add books
def add_books(request):
    #check if user is logged in
    if request.user.is_authenticated:
        #check if user is admin
        if request.user.is_superuser:
            if request.method == "POST":
                form = BookForm(request.POST or None)

                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()
                    return redirect("main:home")
            else:
                form = BookForm()
            return render(request, 'main/addbooks.html', {"form": form, "controller": "Add Books"})

        else:
            return redirect("main:home")
             
    return redirect("accounts:login")
#edit books
def edit_books(request, id):
    #check if user is logged in
    if request.user.is_authenticated:
        #check if user is admin
        if request.user.is_superuser:
            book = Book.objects.get(id=id)

            if request.method == "POST":
                form = BookForm(request.POST or None, instance=book)

                if form.is_valid():
                    data = form.save(commit=False)
                    data.save()
                    return redirect("main:detail", id)
            else:
                form = BookForm(instance=book)
            return render(request, 'main/addbooks.html', {"form":form, "controller": "Edit Books"})
        
        else:
            return redirect("main:home")
             
    return redirect("accounts:login")
#delete books
def delete_books(request, id):
    #check if user is logged in
    if request.user.is_authenticated:
        #check if user is admin
        if request.user.is_superuser:
            book = Book.objects.get(id=id)

            book.delete()
            return redirect("main:home")
        
        else:
            return redirect("main:home")
             
    return redirect("accounts:login")
#adds reviews
def add_review(request, id):
    #check if user is logged in
    if request.user.is_authenticated:
        book = Book.objects.get(id=id)
        if request.method == "POST":
            form = ReviewForm(request.POST or None)
            if form.is_valid():
                data = form.save(commit=False)
                data.comment = request.POST["comment"]
                data.rating = request.POST["rating"]
                data.user = request.user
                data.book = book
                data.save()
                return redirect("main:detail", id)
        else:
            form = ReviewForm()
        return render(request, 'main/details.html', {"form": form})
    else:
        return redirect("accounts:login")
#edits reviews
def edit_review(request, book_id, review_id):
    #check if user is logged in
    if request.user.is_authenticated:
        book = Book.objects.get(id=book_id)
        review = Review.objects.get(book=book, id=review_id)
        #check if the user made the review
        if request.user == review.user:
            if request.method == "POST":
                form = ReviewForm(request.POST, instance=review)
                if form.is_valid():
                    data = form.save(commit=False)
                    if (data.rating > 10) or (data.rating < 0):
                        error = "Out of range. Please select rating from 0 to 10."
                        return render(request, 'main/editreview.html', {"error": error, "form": form})
                    else:
                        data.save()
                        return redirect("main:detail", book_id)
            else:
                form = ReviewForm(instance=review)
            return  render(request, 'main/editreview.html', {"form": form})
        else:
            return redirect("main:detail", book_id)
    else:
        return redirect("accounts:login")
#deletes reviews
def delete_review(request, book_id, review_id):
    #check if user is logged in
    if request.user.is_authenticated:
        book = Book.objects.get(id=book_id)
        review = Review.objects.get(book=book, id=review_id)
        #check if user made the review
        if request.user == review.user:

            review.delete()

        return redirect("main:detail", book_id)
    else:
        return redirect("accounts:login")

main/templates/main/addbooks.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text=center">{{controller}}</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form | crispy}}
                <input type="submit" value="{{controller}}" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Read and Review</title>

  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
        <a class="navbar-brand" href="{% url 'main:home' %}">Read and Review</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'main:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'main:add_books' %}">Add Books</a>
            </li>
            {% endif %} 
            {% if user.is_authenticated %}
            <li class="nav-item dropdown"> 
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{user.username}}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="#">My Profile</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
              </div>
            </li>
            {% else %} 
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:register' %}">Register</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link disabled" href="#"></a>
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'main:home' %}">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="title">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>

    {% block content %}

    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

main/templates/main/details.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
    <br>
    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-4">
                    <img src="{{book.image}}" alt="{{book.name}}" class="img-fluid">
                </div>
                <div class="col-md-8">
                    <h3 class="text-center">
                        {{book.name}}
                    </h3>
                    <p>{{book.description}}</p>
                    <h5>Author: {{book.author}}</h5>
                    <h5>Average Rating: {{average}}/10</h5>

                    {% if request.user.is_authenticated %}
                        {% if request.user.is_superuser %}
                            <a href="{% url 'main:edit_books' book.id %}" class="btn btn-warning">Edit Book</a>
                            <a href="{% url 'main:delete_books' book.id %}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this book?');">Delete Book</a>
                        {% endif %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <br>
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Reviews</h3>
            <form action="{% url 'main:add_review' book.id %}" method="POST">
                {% csrf_token %}
                <label for="comment">Review</label>
                <textarea name="comment" id="comment" cols="30" rows="5" class="form-control"></textarea>

                <label for="rating">Rating</label>
                <input type="range" id="rangeInput"
                name="rating" min="0" max="10" value="0" step="0.5"
                oninput="amount.value=rangeInput.value">
        
        <output name="amount" id="amount" for="rangeInput">0</output>

                <br>
                <input type="submit" class="btn btn-danger" value="Add Review">
            </form>
        </div>
    </div>
    <br>
    <div class="card">
        <div class="card-body">
            <h3 class="text-center">Reviews</h3>
            {% for review in reviews %}
                <div class="card" style="background-color: white;">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3">
                                <h5 class="text-left">{{review.user.username}}</h5>
                                <h5>{{review.rating}}</h5>
                                {% if request.user == review.user %}
                                <a href="{% url 'main:edit_review' book.id review.id%}">Edit</a>
                                <a href="{% url 'main:delete_review' book.id review.id %}" onclick="return confirm('Are you sure you want to delete this review?')">Delete</a>
                                {% endif %}
                            </div>
                            <div class="col-md-9">
                                <p>{{review.comment}}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <br>
            {% endfor %}
        </div>
    </div>
</div>


{% endblock %}

main/templates/main/editreview.html
{% extends 'main/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
    <div class="card">
        <div class="card-body">
            <h3 class="text=center">Edit Review</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form | crispy}}
                {% if error %}
                    <strong style="color: red;">{{ error }}</strong>
                {% endif %}
                <input type="submit" value="Save Changes" class="btn btn-danger">
            </form>
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block content %}

<div class="container">
    <br>
    {% if error %}
        <strong style="color: red;">{{ error }}</strong>
    {% endif %}
    <div class="card">
        <div class="card-body">
            <div class="row">
                {% for book in books %}
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-body">
                            <div class="text-center">
                                <img src="{{book.image}}" alt="" class="img-fluid" width="75%">
                            </div>
                            <h3 class="text-center">
                                {{book.name}}
                            </h3>
                            <div class="text-center">
                                <i class="text-center">{{book.release_date}}</i>
                            </div>
                            <div class="text-center">
                                <a href="{% url 'main:detail' book.id %}">Read More</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>

{% endblock %}